<a href="https://colab.research.google.com/github/ynebin/class2023Fall/blob/main/W6_1006.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Library
* a collection of pre-written codes
* provides various functions and tools

## python standard library
* library that comes bundled with python itself
* available without the need for external installation

In [1]:
import os

print(os.getcwd())  # returns the current working directory

/content


In [2]:
import math

print(math.sqrt(16))  # calculates the square root
print(math.pi)  # a constant that represents π

4.0
3.141592653589793


## external library
* not part of python standard library
* needs to be separately installed with `pip` in the terminal
* created by third-party developers

# numpy
* one of the most fundamental and widely used external libraries
* used for numerical and scientific computing

## numpy array
* fundamental data structure provided by `numpy`
* similar to python lists

In [3]:
import numpy as np

a = np.array([1, 2, 3, 4, -1])

print(a)
print(type(a))
print(a.dtype)

[ 1  2  3  4 -1]
<class 'numpy.ndarray'>
int64


In [4]:
print(a[0])
print(a[2:4])

a[-1] = 5
print(a)

1
[3 4]
[1 2 3 4 5]


## element-wise calculations

In [5]:
a = np.array([1, 2, 3])

print(f"a + 2: {a + 2}")
print(f"a - 2: {a - 2}")
print(f"a * 2: {a * 2}")
print(f"a / 2: {a / 2}")
print(f"a ** 2: {a ** 2}")

a + 2: [3 4 5]
a - 2: [-1  0  1]
a * 2: [2 4 6]
a / 2: [0.5 1.  1.5]
a ** 2: [1 4 9]


In [6]:
b = np.array([2, 3, 4])

print(f"a + b: {a + b}")
print(f"a - b: {a - b}")
print(f"a * b: {a * b}")
print(f"a / b: {a / b}")
print(f"a ** b: {a ** b}")

a + b: [3 5 7]
a - b: [-1 -1 -1]
a * b: [ 2  6 12]
a / b: [0.5        0.66666667 0.75      ]
a ** b: [ 1  8 81]


## basic functions
* `np.sum`: returns sum of the elements
* `np.mean`: returns mean of the elements
* `np.min`: returns the smallest element
* `np.max`: returns the largest element

In [7]:
# a = np.array([1, 2, 3])

print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))

6
2.0
1
3


* `np.zeros`: creates an array filled with zeros
* `np.ones`: creates an array filled with ones

In [8]:
print(np.zeros(2))
print(np.ones((2, 2)))

[0. 0.]
[[1. 1.]
 [1. 1.]]


## speed

In [9]:
import time

a = [i for i in range(1000000)]
b = np.array(a)

start_time = time.time()
a = [i**2 for i in a]
end_time = time.time()

list_time = end_time - start_time
print(f"list: {list_time}")

start_time = time.time()
b = b**2
end_time = time.time()

np_time = end_time - start_time
print(f"numpy: {np_time}")

list: 0.32639575004577637
numpy: 0.004053831100463867


## multi-dimensional array

In [10]:
# single dimension (1D)

a = np.array([1, 2, 3])

print(a)
print(f"shape of a: {a.shape}")

[1 2 3]
shape of a: (3,)


* 3x2 2D matrix (3 rows x 2 columns)


||column 0|column 1|
|-|-|-|
|**row 0**|1|2|
|**row 1**|3|4|
|**row 2**|5|6|

In [11]:
# multi dimension (2D)

b = np.array([[1, 2], [3, 4], [5, 6]])

print(b)
print(f"shape of b: {b.shape}")

[[1 2]
 [3 4]
 [5 6]]
shape of b: (3, 2)


In [12]:
print(f"row 0: {b[0, :]}")
print(f"row 1: {b[1, :]}")
print(f"row 2: {b[2, :]}")

row 0: [1 2]
row 1: [3 4]
row 2: [5 6]


In [13]:
print(f"column 0: {b[:, 0]}")
print(f"column 1: {b[:, 1]}")

column 0: [1 3 5]
column 1: [2 4 6]


In [14]:
print(b[0, 0])
print(b[0, 1])
print(b[1, 0])
print(b[1, 1])
print(b[2, 0])
print(b[2, 1])

1
2
3
4
5
6


### np.matmul
* performs matrix multiplication

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])

print(a)
print(f"shape of a: {a.shape}")
print(b)
print(f"shape of b: {b.shape}")

[[1 2 3]
 [4 5 6]]
shape of a: (2, 3)
[[1 2]
 [3 4]
 [5 6]]
shape of b: (3, 2)


`a`

|1 2 3|<br />
|4 5 6|


`b`

|1 2|<br />
|3 4|<br />
|5 6|


`np.matmul(a, b)`

|1`*`1`+`2`*`3`+`3`*`5 &nbsp;&nbsp;&nbsp;1`*`2`+`2`*`4`+`3`*`6|<br />
|4`*`1`+`5`*`3`+`6`*`5 &nbsp;&nbsp;&nbsp;4`*`2`+`5`*`4`+`6`*`6|

In [16]:
c = np.matmul(a, b)

print(c)
print(f"shape of c: {c.shape}")

[[22 28]
 [49 64]]
shape of c: (2, 2)


### .reshape
`a.reshape(b)`

* changes the shape of an array

In [17]:
print(f"{a}\n")
print(a.reshape((3, 2)))

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


### np.transpose
`np.transpose(a)`

* flips the shape of an array along its axes

||student A|student B|student C|
|-|-|-|-|
|**test 1**|60|81|99|
|**test 2**|85|77|95|

In [18]:
a = np.array([[60, 85], [81, 77], [99, 95]])
b = np.transpose(a)

print(f"{a}\n")
print(b)

[[60 85]
 [81 77]
 [99 95]]

[[60 81 99]
 [85 77 95]]


### axis

In [19]:
print(np.mean(b, axis=0))  # each student's mean score
print(np.mean(b, axis=1))  # each test's mean score

[72.5 79.  97. ]
[80.         85.66666667]


## real-world data as numpy array

### image

In [20]:
from PIL import Image

img_url = "https://raw.githubusercontent.com/ynebin/class2023Fall/main/cat.jpeg"
os.system("curl " + img_url + " > cat.jpeg")

a = Image.open("/content/cat.jpeg")
a = np.array(a)

print(f"shape of a: {a.shape}")
print(a)

shape of a: (4000, 6000, 3)
[[[ 23  58  34]
  [ 26  61  37]
  [ 26  61  37]
  ...
  [ 47 109  60]
  [ 48 110  61]
  [ 52 114  65]]

 [[ 24  59  35]
  [ 26  61  37]
  [ 26  61  37]
  ...
  [ 51 113  64]
  [ 52 114  65]
  [ 56 118  69]]

 [[ 26  61  37]
  [ 27  62  38]
  [ 26  61  37]
  ...
  [ 54 117  70]
  [ 54 117  70]
  [ 56 119  72]]

 ...

 [[ 92 123  55]
  [ 91 122  54]
  [ 92 123  55]
  ...
  [ 59  85  37]
  [ 62  88  40]
  [ 62  88  40]]

 [[ 90 121  53]
  [ 90 121  53]
  [ 92 123  55]
  ...
  [ 63  89  41]
  [ 66  92  44]
  [ 63  89  41]]

 [[ 89 120  52]
  [ 91 122  54]
  [ 94 125  57]
  ...
  [ 64  90  42]
  [ 65  91  43]
  [ 58  84  36]]]


### audio

In [21]:
import librosa

audio_url = "https://raw.githubusercontent.com/ynebin/class2023Fall/main/aeiou.wav"
os.system("curl " + audio_url + " > aeiou.wav")

a, sr = librosa.load("aeiou.wav")

print(type(a))
print(f"shape of a: {a.shape}")
print(a)

<class 'numpy.ndarray'>
shape of a: (48600,)
[0.00135931 0.0020927  0.00200758 ... 0.0021776  0.00213208 0.00217898]
